#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


for v in *.c
do
    nome=`echo $v| sed 's/.c//'`

    if test -d $nome
	then
		:
	else
                 mkdir $nome
    fi
    cp $v $nome
    cd $nome
    if newsp  $v
    then
        :
    else
        echo "newsp: nao consegui pre-processar arquivo $v!"
        echo "$v -- FALHOU newsp!" >> fail.log
    fi
    if newpoketool t_$v -f_todas_
    then
       echo "$v -- OK!"
       cp testeprog.c $nome-poke.c
    else
       echo "$v -- FALHOU" >> fail.log
    fi
      
    cd ..
done
 