#!/bin/sh -x

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


echo 'calcnos - Gerador dos Grafos de Fluxo de Programa de um <arquivo>.c'
echo 'calcnos - Gera os arquivos tmp_<arquivo>.li, tmp_<arquivo>.nli'
echo '          e .gfc do <arquivo>.c'

case $# in

0) echo '' 
   echo 'Uso: calcnos <arquivo>.c'  1>&2  ;
   exit 2;;
esac


nome=`echo $1| sed 's/.c//'`

\rm -f tmp_$1

if $CC -E $1 -o tmp_$1
then
	echo "MSG: Pre'-processdor gerou arquivo \"tmp_$1\"."
	nome=`echo tmp_$1| sed 's/.c//'`
	if newli -t $nome c 
	then
	\rm -f tipos.tes
	echo "MSG: \"li\" bem sucedida gerou arquivo \"$nome.li\"."
		if newchanomat -t $nome 
		then
		echo "MSG: \"chanomat\" gerou arquivo \"$nome.nli\"."
		echo "MSG: \"$nome.nli\" esta' pronto para visualizacao de nos."
		else
		echo "ERRO: \"chanomat\" nao conseguiu gerar arquivo \"$nome.nli\"."
		fi
	else
	echo "ERRO: \"li\" nao conseguiu gerar arquivo \"$nome.li\"."
	fi
else
	echo "ERRO: Nao consegui rodar o preprocessador da linguagem C"
fi
