#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



# Consumidor

while test -f cur-exec
 do

   while test -f end-test-case
   do      
      sleep 10
   done

   touch cur-aval

   syncaval-Sort > /dev/null
   rm -f cur-aval
      
 done
