#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


############################################################################
#									   #
# exec-batch -- Shell file to invoke several test cases in batch.       #
#									   #
#									   #
#									   #
############################################################################

echo 'exec-batch - execucao em batch de casos de testes'

case $# in

0) echo 'Uso: exec-batch <nome do executavel> <dir casos de teste>  x y [+l|-l] [+t|-t]'  1>&2  ;
   exit 2;;
1) echo 'exec-batch Erro: numero incorreto de parametros!' 1>&2 ; exit 2;;
2) echo 'exec-batch Erro: numero incorreto de parametros!' 1>&2 ; exit 2;;
3) echo 'exec-batch Erro: numero incorreto de parametros!' 1>&2 ; exit 2;;
4) echo 'exec-batch Erro: numero incorreto de parametros!' 1>&2 ; exit 2;;
*) nome_exe=$1; dir_tcase=$2; beg=$3; end=`expr $4 + 1`; lastcase=$4;

esac

# Get functions name 

shift
shift
shift
shift

while test "$1" != ""
do
        case $1 in
        -l) linepars="$linepars $1";;
        +l) linepars="$linepars $1";;
        -t) linepars="$linepars $1";;
        +t) linepars="$linepars $1";;
         *) funcs="$funcs $1"
        esac
        shift
done

# First test if there is executable

if  test -f $nome_exe
then
	:
else
	echo "exec-batch: Erro: Nao encontrei o executavel em \"$nome_exe\""
	exit 2
fi

if test -d ./output
then
	echo "exec-batch: Msg: diretorio de saidas ja' existe"
else
	echo "exec-batch: Msg: Criando o diretorio de saidas"
	mkdir ./output
fi
	
#echo $dir_exe $dir_tcase $beg $end

#echo 'passei aqui'

inicio=$beg


while test "$beg" != "$end"
do

	echo ''
	echo "		**** Executando Caso de Teste Numero $beg ****"
	echo ''

	if cat $dir_tcase/input$beg | exec-aux $nome_exe $linepars -r$beg $funcs #> $dir_exe/output/output$beg
	then
		:
else
	   echo "exec-batch: Erro: Nao consegui executar caso de teste $beg"
	   
	fi

        beg=`expr $beg + 1`
done


# Para garantir o termino de consumer

rm -f cur-exec
rm -f path.tes
rm -f end-test-case

exit 0










