#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


############################################################################
#									   #
# genflow -- Shell file to produce flow graphs of C functions.    	   #
#									   #
# author:  Marcos L. Chaim						   #
# date:    1994/12/28							   #
# version: 1.0   							   #
#									   #
############################################################################

case $# in

0) echo 'Uso: genflow <C file>'  1>&2  ;
   exit 2;;
esac

# Set Trap routine

trap ' # Clean up intermediate files before leaving
   if -f temp$$ then 
	rm -f temp$$
   fi
   exit 3
' 1 2 9 15

# Separe file name

archive=$1
echo "Arquivo em teste: $archive"

# Obtain the preprocessed file

if $CC -E $includes $defines $archive -o tmp_$archive 
then
    echo "* * $archive pre-processado * *"
    sed '/^#/d' tmp_$archive > tmp1$$
    mv tmp1$$ tmp_$archive
    rm -f tmp1$$
    archive=tmp_$archive
    echo $archive
else
    echo "genflow erro: erro no pre-processamento $archive"
    exit 1
fi
		
# Obtain filename without extention

filename=`echo $archive | sed 's/\.c//'` 


# Firts pass, clean up all file from previous invocation of genflow

rm -f *.nli *.li *.gfc

#set value of return
erro=0

if newli -t $filename c $includes $defines
then   
    if newchanomat $filename
    then
         echo "genflow: Grafos de Fluxo de Controle gerados ok."
    else
         echo "genflow erro: problemas na geracao do grafo de fluxo de controle"
	 erro=7
    fi
else
   echo "genflow erro: problemas na geracao da linguagem intermediaria"
fi

rm -f tipos.tes

exit $erro




