#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


case $# in
0|1|2|3|4) echo 'newpokeaval-batch <begin> <end> -ffunc [-ffunc] -pu|-pudu|-pdu|-arcs|-nos|-puses|-uses|-du'  1>&2  ; exit 2;;
esac

# Get functions name 

beg=$1
end=$2

shift
shift


while test "$1" != ""
do
        case $1 in
         -pu|-pudu|-pdu|-arcs|-nos|-puses|-uses|-du) criteria="$criteria $1";;
         *) funcs="$funcs $1"
        esac
        shift
done


for mod in  `echo $funcs | sed 's/-f//g'`
	do
	if test -d $mod
	then
		:
	else
		echo "Erro : diretorio \"$mod\" nao existe"
		exit 2
	fi
	done


for mod in  `echo $funcs | sed 's/-f//g'`
  do
  echo "Funcao $mod:"
  if newpokeaval -d$mod  -ns $criteria $beg to $end
  then
     :
  fi

  done

exit 0




