#!/bin/sh

# Copyright 2012 Marcos Lordello Chaim, José Carlos Maldonado, Mario Jino, 
# CCSL-ICMC <ccsl.icmc.usp.br>
# 
# This file is part of POKE-TOOL.
# 
# POKE-TOOL is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


nome=`echo $1| sed 's/.c//'`

echo $1
echo $2
if $CC -E  -DE7 -DE8 -DE10 -DE12 -DE14 -DE16 -DE17 -DE18 -DE19 -DE20 -DE21 -DE22 -DE23 -DE24 -DE25 -DE27 -DE29 -DE33 $1 -o t_$1
then
	
	echo "Gerei t_$1"
	exit 0
else
	echo " Nao consegui rodar o preprocessador da linguagem C"
	exit 1
fi
